# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_utils.ipynb.

# %% auto 0
__all__ = ['get_next_trading_day']

# %% ../00_utils.ipynb 4
from fastcore.all import *
from datetime import timedelta

# %% ../00_utils.ipynb 5
def get_next_trading_day(dte,unique_dates,dates_dict):
    for i in range(10):
        out = dates_dict.get(dte+timedelta(i),False) 
        if out != False: return unique_dates[out]
    return None
